### ISSUE TITLE
Unable to export html: higlass-text@%5E0.1.1:1 Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by superbsky** [gosling-lang/gosling.js#1103]
I am trying to export an example from [Gosling.js](https://gosling.js.org/), but when I try to open the saved HTML file, I get the following error in the developer console:

gosling.js@0.17.0:14 
       GET https://esm.sh/higlass-text@%5E0.1.1?target=es2022 net::ERR_ABORTED 404 (Not Found)

When I try to open [this URL](https://esm.sh/higlass-text@%5E0.1.1?target=es2022) directly, it shows that the module is not found.

**Comment by dvdkouril** [comment]
Hi, I see what you mean.

@sehilyi Could this be related to [this issue](https://github.com/higlass/higlass-text/pull/3) brought up by @etowahadams in higlass-text? When I try loading `https://esm.sh/higlass-text/es/index.js` you do get the module back.

**Comment by superbsky** [comment]
@dvdkouril @sehilyi @etowahadams is there any workaround available? We've hit a roadblock and cannot use [gosling.js](https://github.com/gosling-lang/gosling.js) for the current project.

**Comment by dvdkouril** [comment]
If you want a quick and dirty trick to make individual exported HTML files work, this seems to work on my side:

Edit the downloaded `.html` file and make two edits (look at the commented files):
```html
    <script type="importmap">
      {
        "imports": {
          "react": "https://esm.sh/react@18",
          "react-dom": "https://esm.sh/react-dom@18",
          "pixi": "https://esm.sh/pixi.js@6",
          "higlass-text": "https://esm.sh/higlass-text/es/index.js", // 1. add this line
          "higlass": "https://esm.sh/higlass@1.13.4?external=react,react-dom,pixi",
          "gosling.js": "https://esm.sh/gosling.js@0.17.0?external=react,react-dom,pixi,higlass,higlass-text" // 2. add higlass-text to external here
        }
      }
    </script>

```

https://github.com/user-attachments/assets/c49e79e9-d528-4113-9e31-712bb626cca2

**Comment by superbsky** [comment]
@dvdkouril worked like a charm!

**Comment by sehilyi** [comment]
I think we need to edit the html template accordingly before the higlass-text is fixed there.

**Comment by dvdkouril** [comment]
I only quickly looked into this, I'm definitely not an expert in js package distribution:
- esm.sh [published an update this January](https://github.com/esm-dev/esm.sh/releases/tag/v136), there's a bunch of changes that could lead to interpreting the `package.json` of `higlass-text` differently, since the standards have probably evolved since the last release in Dec 2022.
- [Etowah's PR](https://github.com/higlass/higlass-text/pull/3) suggested changing the `"main"` field from `"./src/index.js"` to `"./es/index.js"`, but wouldn't that break the non-ES build imports?
- [higlass-text/package.json](https://github.com/higlass/higlass-text/blob/master/package.json) is not using the `export` field, which as far as I've learned now, should be the modern alternative no main. Using [conditional exports](https://nodejs.org/api/packages.html#conditional-exports) is probably what we need to happen in higlass-text.

Is the HTML export in Gosling the only way Higlass is used through the esm.sh CDN? There doesn't seem to be any reports of it breaking anywhere else.

Edit: It seems that higlass-text tries to point to the `es` folder by using the `"module"` field, which [apparently has never been standardized](https://stackoverflow.com/questions/68572936/what-is-the-difference-between-main-and-module-vs-exports-in-package-json).

**Comment by manzt** [comment]
> but wouldn't that break the non-ES build imports?

Not sure about this. My hunch is no, since the `unpkg` key still exists... The other reason being that `main` doesn't actually point to a existing file in the package distribution.

**Comment by dvdkouril** [comment]
Should `main` point to the build directories or the source folder? That's what felt weird to me, pointing to an `./es/` path in `main`.

Anyway, do I understand it correctly that using `export` field would be the better way to specify this?

**Comment by manzt** [comment]
`main` _should_ point to either CommonJS or ESM (if `"type": "module"` in `package.json`), both of which `src` here is not. 

It is somewhat of an anti-pattern to publish (source) code that requires additional transformation to actually run in a JavaScript runtime. For example, you wouldn't publish TypeScript source as `main` (to npm).

The source code for `higlass-text` is some combination of ESM (i.e`import`/`export`) with CommonJS-based resolution (i.e., `'./scripts`' pointing to `'./scripts/index.js'`), which no runtime I'm aware of will actually be able to load (maybe Bun).

> Anyway, do I understand it correctly that using export field would be the better way to specify this?

With that said, I do think `"exports"` being a new piece of metadata would potentially be a better way to specify the ES entrypoint as it is a new field that something like `esm.sh` respects but likely is ignored by other legacy systems (which may rely on `main` returning a 404 and resolving to something else).

**Comment by dvdkouril** [comment]
Okay, very useful info, thank you!!
