### ISSUE TITLE
`Encoding` type not included in generated JSON schema

### ISSUE THREAD

**Issue by manzt** [gosling-lang/gosling.js#565]
Although we created a new `Encoding` type in #533, it doesn't seem to end up as a definition in the generated JSON schema. I'm not sure if there is away to force this behavior, but it would be useful for

- https://github.com/gosling-lang/gos/pull/71

**Comment by sehilyi** [comment]
~~Just realized we have not released `gosling.js` after we made the update on the `Encoding`. I can release the latest version so that the updated schema can be visible to the `gos` package.~~

@manzt I just released v0.9.9, and the updated `Encoding` should be accessible. Apologize that it took some time to release the new version.

**Comment by manzt** [comment]
No worries! I just checked out https://github.com/gosling-lang/gosling.js/blob/v0.9.9/schema/gosling.schema.json, but still can't seem to find `Encoding` unfortunately.

**Comment by sehilyi** [comment]
As part of the post-v1 release, we are cleaning up GitHub issues. Please feel free to reopen this issue if you believe it is still relevant!
